### ISSUE TITLE
WMS harvesting is not working

### ISSUE THREAD

**Issue by SterckxArnaud** [kartoza/IGRAC-GGIS#618]
Dear Irwan, I noticed that the layers that we fetch through WMS services from external websites are not available anymore. See for instance https://ggis.un-igrac.org/catalogue/#/?f=dataset&q=whymap
I tried to restore the service but it does not work https://ggis.un-igrac.org/services/1871/
Could you please have a look?

**Comment by meomancer** [comment]
hi @NyakudyaA 
Could you help me check this?

**Comment by NyakudyaA** [comment]
There are a couple of errors that have been flagged here
https://ggis.un-igrac.org/en-us/admin/harvesting/asynchronousharvestingsession/9/change/

I think the best way would be to delete those sessions but I am not sure if those layers are being used in maps or other places

**Comment by SterckxArnaud** [comment]
Hi Admire, you can delete these sessions, they are from a few days ago when I tried to restore the WMS connections (without success).

**Comment by NyakudyaA** [comment]
@meomancer I have checked this and it seems to always error on 
```
state: FAILURE
result: IntegrityError('duplicate key value violates unique constraint "layers_dataset_store_workspace_name_0b4228a1_uniq"\nDETAIL: Key (store, workspace, name)=(httpsservicesbgrdewmsgrundwasserwhymap_gwr, remoteWorkspace, 11) already exists.\n')
traceback: None
```

This error has already been reported and fixed here https://github.com/geosolutions-it/nexus-geonode/issues/496

I believe we might have to delete the service and register it again. @SterckxArnaud Are those layers being used in maps or geostories ?

**Comment by SterckxArnaud** [comment]
> I believe we might have to delete the service and register it again. @SterckxArnaud Are those layers being used in maps or geostories ?

Yes, but most of them can be deleted. The following wms need to be preserved:
https://www.gapmaps.org/geoserver/wms
https://sig.lneg.pt/server/services/CartaGuine/MapServer/WMSServer
http://mapsref.brgm.fr/wxs/1GG/IGC35_CGMW_BRGM_Africa_Geology?

**Comment by Jeremy-Prior** [comment]
[https://sig.lneg.pt/server/services/CartaGuine/MapServer/WMSServer](https://sig.lneg.pt/server/services/CartaGuine/MapServer/WMSServer) is working:
![image](https://github.com/kartoza/IGRAC-GGIS/assets/100694811/bb499e49-ec01-433a-8f49-bf9246bc9776)

[http://mapsref.brgm.fr/wxs/1GG/IGC35_CGMW_BRGM_Africa_Geology](http://mapsref.brgm.fr/wxs/1GG/IGC35_CGMW_BRGM_Africa_Geology) is also working:
![image](https://github.com/kartoza/IGRAC-GGIS/assets/100694811/1950ab87-4117-412a-8658-d9a92d6df6ae)

[https://www.gapmaps.org/geoserver/wms](https://www.gapmaps.org/geoserver/wms) still has an issue, is it possible the source url has changed? It is not a recognised remote service:
![image](https://github.com/kartoza/IGRAC-GGIS/assets/100694811/bd014fa6-009a-4f60-8697-530aa8d5e3bb)

**Comment by SterckxArnaud** [comment]
Thank you Jeremy! I checked the gapmap platform and I can't see the layers indeed, it seems that they are not available. @clau1313, could you please check with Joel if everything is OK on their side?

**Comment by robertohuru** [comment]
@meomancer it is still not possible to harvest from https://www.gapmaps.org/geoserver/wms because of timeout.

@clau1313 did you check on this with Joel?

**Comment by clau1313** [comment]
Hi @meomancer, sorry for my very late reply. Could you please try again? It seems that they changed something, the layers are loading fast and nicely from https://www.gapmaps.org/Home/Public

**Comment by EliVolsch** [comment]
@robertohuru can we please revisit this issue?

**Comment by meomancer** [comment]
This is still blocked as https://www.gapmaps.org/geoserver/wms still timeout
We need ask them to improve it

**Comment by clau1313** [comment]
hi @meomancer, I am not sure how relevant this ticket is anymore. The problem is that we couldn't load the layers from GAP maps in our Groundwater Quality map viewer, but now it's is possible, as you can see here (the blue layer, Global Arsenic, is coming from GAP maps).

![Image](https://github.com/user-attachments/assets/e08bfb14-21f4-4e1c-a286-90c4ed5490fe)

So, if there is nothing else that is impacted by this wms time out, I suggest to close this ticket.

**Comment by meomancer** [comment]
Hi @clau1313 cc @EliVolsch 
The harvester is still not working 
https://ggis.un-igrac.org/services/2208/

![Image](https://github.com/user-attachments/assets/eabe7eee-8139-47b6-bf37-edf9461a28b9)

It seems the above layer is from old layer
I think the goal is here is we pull the new layer from their side

**Comment by clau1313** [comment]
hi @meomancer but which one is the new layer? or you mean a different new layer?

because now I am looking at their website and it would be nice to retrieve 2 new layers from them: From GAP layers, arsenic and fluoride concentrations, global database:

![Image](https://github.com/user-attachments/assets/06096341-9607-4ec5-936f-d21cceef5a55)

I can ask them to have a look. Any advice on what exactly I should ask them?

**Comment by EliVolsch** [comment]
@meomancer: Please send details to ask for

**Comment by clau1313** [comment]
thanks @meomancer, I just sent a request to Eawag, I will let you know when they reply.
