### ISSUE TITLE
New layer for Austrian data looks empty

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/IGRAC-GGIS#905]
Good afternoon,

I created a layer to show data from the organisation "Austria - Federal Ministry of Agriculture_ Forestry_ Regions and Water Management" separately, however, the layer appears empty:

![Image](https://github.com/user-attachments/assets/6dcab4eb-0dc3-40d9-962b-17c5b27e92b7)

I created it using this link:
https://ggis.un-igrac.org/en-us/admin/igrac/groundwaterlayer
 
I selected "well type": GGMN, but when I come back to check it, it appears that "well and monitoring" is selected, and every time I tried to change it, it comes back to well and monitoring instead of GGMN. Not sure if that's the problem.

![Image](https://github.com/user-attachments/assets/66a305ff-5af8-4c24-9f40-b713de35b2f8)

Can you please help me? Thank you.
Cheers,
Claudia

**Comment by meomancer** [comment]
Hi @clau1313 
Fixed

The new dataset : https://ggis.un-igrac.org/catalogue/#/dataset/2546

We can't have comma in the name of layer, so we need to remove it
I will update the form to have this name validation, but for now, we can't put comma on the name

**Comment by clau1313** [comment]
hi @meomancer, I was checking the layer again and when I click on a point, the panel on the right looks like this:

<img width="690" height="699" alt="Image" src="https://github.com/user-attachments/assets/08898b86-6a45-4f7d-bc46-bad416865fa8" />

can you please check why it appears unformatted?

**Comment by meomancer** [comment]
Hi @clau1313 
How did you do that?
It is working from my side

<img width="2496" height="1450" alt="Image" src="https://github.com/user-attachments/assets/c637736e-1a16-4773-a092-3b81b7329729" />

Could you try hard refresh?

**Comment by clau1313** [comment]
hi @meomancer, I don't know, it was just like that, I didn't do anything. But now it's looking fine again, so I guess it was a temporary issue. Thanks for checking!

**Comment by clau1313** [comment]
Hi @meomancer, the problem is back:

<img width="1611" height="805" alt="Image" src="https://github.com/user-attachments/assets/34917a88-19db-4bb2-a837-8172d59392dc" />

Maybe it's related to the fact that I am calling the points from the GGMN and not directly from the layer? The GGMN layers looks fine:

<img width="1602" height="790" alt="Image" src="https://github.com/user-attachments/assets/5ad52c09-94a9-4920-9231-b04c5a1ece7a" />

But the Netherlands layer has the same issue:

<img width="1599" height="781" alt="Image" src="https://github.com/user-attachments/assets/a9915766-8b08-4e13-b1bd-30963781e559" />

**Comment by meomancer** [comment]
Hi @clau1313 
Fixed:
- This is bug from geonode, which is not bring the template to the others layers
- I have fixed it manually on django admin
- I think we can do this for now (as fixing it on the code will take time)

Please check it @clau1313
